version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: obelisk_dex_admin
      POSTGRES_PASSWORD: hmtmUh8r0tJheehpqu1L
      POSTGRES_DB: ton_dex
    volumes:
      - ./app/database_dump/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./app/database_dump/obelisk_db.sql:/docker-entrypoint-initdb.d/obelisk_db.sql
    ports:
      - "5433:5432"

  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
